# write a github workflow to print the /etc/hosts file to the console of an ubuntu-latest runner

name: Runner Hosts

on:
  workflow_dispatch:
  
jobs:
    build-win:
        runs-on: windows-latest
    
        steps:
        - uses: actions/checkout@v3
  
        - name: Print /etc/hosts on windows runner
          run: cat /etc/hosts

    build-mac:
        runs-on: macos-latest
    
        steps:
        - uses: actions/checkout@v3
  
        - name: Print /etc/hosts on macos runner
          run: cat /etc/hosts

    build-ubuntu:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v3
  
        - name: Print /etc/hosts on ubuntu runner
          run: cat /etc/hosts